1. SELECT FIRST_NAME, LAST_NAME, SALARY FROM hr.employees
   ORDER BY SALARY DESC LIMIT 1;

2. SELECT MAX(SALARY) - MIN(SALARY) AS SALARY_DIFF FROM hr.employees;

3. SELECT ROUND(AVG(SALARY)) AS SALARY_AVERAGE FROM hr.employees
   GROUP BY JOB_ID
   ORDER BY SALARY_AVERAGE DESC;

4. SELECT SUM(SALARY) AS EVERYONES_PAYMENT FROM hr.employees;

5. SELECT MAX(SALARY) SALARY_MAX, MIN(SALARY) SALARY_MIN, SUM(SALARY) SALARY_SUM, ROUND(AVG(SALARY), 2) SALARY_AVERAGE
   FROM hr.employees;

6. SELECT COUNT(*) AS 'NUMBER OF IT_PROG EMPLOYEES' FROM hr.employees
   WHERE JOB_ID = 'IT_PROG';

7. SELECT JOB_ID, SUM(SALARY) AS TOTAL_PAYMENT FROM hr.employees
   GROUP BY JOB_ID;

8. SELECT JOB_ID, SUM(SALARY) AS TOTAL_PAYMENT FROM hr.employees
   GROUP BY JOB_ID
   HAVING JOB_ID = 'IT_PROG';

9. SELECT JOB_ID, ROUND(AVG(SALARY), 2) AS AVERAGE_SALARY FROM hr.employees
   GROUP BY JOB_ID
   HAVING JOB_ID <> 'IT_PROG'
   ORDER BY AVERAGE_SALARY DESC;

10. SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2) AS AVERAGE_SALARY, COUNT(*) AS EMPLOYEE_QUANTITY FROM hr.employees
    GROUP BY DEPARTMENT_ID
    HAVING EMPLOYEE_QUANTITY > 10;

11. SET sql_safe_updates = 0;
    UPDATE hr.employees
    SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777');

12. SELECT * FROM hr.employees
    WHERE CHAR_LENGTH(FIRST_NAME) > 8;

13. SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) AS HIRE_YEAR FROM hr.employees;

14. SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) AS HIRE_DAY FROM hr.employees;

15. SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) AS HIRE_MONTH FROM hr.employees;

16. SELECT UPPER(FIRST_NAME) AS FIRST_NAME FROM hr.employees;

17. SELECT LAST_NAME, HIRE_DATE FROM hr.employees
    WHERE MONTH(HIRE_DATE) = 7
    AND YEAR(HIRE_DATE) = 1987;

18. SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) AS 'Time in Company (Days)' FROM hr.employees;